### ISSUE TITLE
'*' is not allowed as first char of a property

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit-cssparser#15]
I see the css parsing error as the title in htmlunit but don't see error in browser. The css is:
```css
.clearfix {
    zoom:1;*display: inline-block
}
```
